### ISSUE TITLE
Problem with long ISI

### ISSUE THREAD

**Issue by Masharipov** [neurolabusc/fMRI-Simulator#1]
Dear Chris,
Thanks for this usefull software!

For short and medium ISI, everything is fine.
Hovewer, I ran into a problem when generating designs with a long ISI.
For example, for an event-related design with random ISI (minimum = 15000ms, mean = 17000ms, 100 iterations), 2 conditions and 17000 volumes, the actual ISI generated by fmrisim becomes fixed at 15000ms. As far as I understand, the actual ISI becomes variable only for a minimum ISI less than 10000 ms.

Can you please tell me how to solve this problem?

**Comment by neurolabusc** [comment]
The inputs are bounded to 15000. You can simply increase this value if you wish by editing the [code](https://github.com/neurolabusc/fMRI-Simulator/blob/11f213a9ddb1ce8de7d5180f4d3e809e9d49a4c6/source/gui.pas#L118) and recompiling. In general, extremely long interstimulus intervals will be inherently inefficient, as you have fewer observations and you are not taking advantage of the fact that the HFR is largely additive.

```
     lFMRI.TRmsec := GetInt(TREdit.Text,1,2000,15000);
     lFMRI.Volumes := GetInt(VolEdit.Text,1,2000,15000);
     lFMRI.nCond := GetInt(CondEdit.Text,1,2000,15000);
     lFMRI.meanISI := GetInt(MeanISIEdit.Text,2,2000,15000);
     lFMRI.minISI := GetInt(MinISIEdit.Text,1,lFMRI.meanISI div 2,lFMRI.meanISI-1);
     lFMRI.nPermute := GetInt(PermuteEdit.Text,0,2000,15000);
     lFMRI.Iterations := GetInt(IterationEdit.Text,0,2000,15000);
```

**Comment by Masharipov** [comment]
Thanks a lot!
